### ISSUE TITLE
Include Python -> Spark .NET wrapper logic in shrike

### ISSUE THREAD

**Issue by dkmiller** [Azure/shrike#30]
Currently, most AML HDI components include similar boilerplate to:

- Fully resolve the path to the zipped Spark .NET code
- Create a Java "gateway" array
- Populate that array using provided command line arguments
- Pass the arguments to the Dotnet runner, catching and re-throwing any exception.

(An example of this boilerplate is included below.)

**Recommendation:** the shrike package should expose a Python "wrapper" for handling this logic.

Rough proposal for what the "after" logic would look like (**Note:** this is for inspiration only, not necessarily precise API requirement.)

**run.py**

```python
from shrike.hdi import spark_net_wrapper

if __name__ == "__main__":
    # This would have optional parameters for passing in arguments, configuring compliant logging.
    spark_net_wrapper(zip_name="MyCoolCompiledBinaries.zip")
```

----

Example boilerplate Python code.

```python
try:
    j_args = SparkContext._gateway.new_array(spark._jvm.java.lang.String, 4)

    j_args[0] = get_zip_file(spark)
    j_args[1] = "canary-hdi"
    j_args[2] = "--input"
    j_args[3] = args.input_path

    # TODO: why doesn't the naive print statement work?
    log.info(
        f"Calling dotnet with arguments: {j_args[0]} {j_args[1]} {j_args[2]} {j_args[3]}",
        category=DataCategory.PUBLIC,
    )
    spark._jvm.org.apache.spark.deploy.dotnet.DotnetRunner.main(j_args)
except py4j.protocol.Py4JJavaError as err:
    log.error(f"Error message: {err.errmsg}", category=DataCategory.PUBLIC)
    log.error(f"Java exception: {err.java_exception}", category=DataCategory.PUBLIC)

    raise
```

**Comment by dkmiller** [comment]
How to handle: https://github.com/bartdag/py4j/issues/306 ?

```
SystemLog: before import statements.
SystemLog: after import statements.
SystemLog:INFO:__main__:Running module with arguments Namespace(in_file_type='csv', input_path='foo', out_file_type='json', output_path='wasbs://azureml-blobstore-62d1e179-cf1d-4112-b5d5-518fcdbfb139@amlstoragexdjqlwufhgfss.blob.core.windows.net/azureml/40fa36dd-682b-4b85-a358-368418b8b59a/output_path', percent_take=100, try_spark_net=True)
SystemLog:INFO:__main__:Running with Python version 3.7.7
SystemLog:INFO:__main__:application name: aml-ds-hdi-canary-2021-06-04 21:20:38
SystemLog:INFO:__main__:Trying to run Spark .NET code
SystemLog:INFO:spark_net:foo
SystemLog:WARNING:spark_net:Searching py_files for canary-hdi.zip: wasbs://hdijobshare@amlstoragexdjqlwufhgfss.blob.core.windows.net/40fa36dd-682b-4b85-a358-368418b8b59a/canary-hdi.zip,wasbs://hdijobshare@amlstoragexdjqlwufhgfss.blob.core.windows.net/40fa36dd-682b-4b85-a358-368418b8b59a/spark_net.py
SystemLog:INFO:spark_net:Calling dotnet with arguments: ['wasbs://hdijobshare@amlstoragexdjqlwufhgfss.blob.core.windows.net/40fa36dd-682b-4b85-a358-368418b8b59a/canary-hdi.zip', 'canary-hdi', '--input', 'foo']
SystemLog: Creating Spark session.
[2021-06-04T21:21:03.9644443Z] [wn2-hdic5c] [Info] [ConfigurationService] Using port 33965 for connection.
[2021-06-04T21:21:03.9656808Z] [wn2-hdic5c] [Info] [JvmBridge] JvMBridge port is 33965
[2021-06-04T21:21:03.9683282Z] [wn2-hdic5c] [Info] [JvmBridge] The number of JVM backend thread is set to 10. The max number of concurrent sockets in JvmBridge is set to 7.
SystemLog: Spark session: Microsoft.Spark.Sql.SparkSession
SystemLog: Reading input data: foo
[2021-06-04T21:21:04.2910891Z] [wn2-hdic5c] [Error] [JvmBridge] JVM method execution failed: Nonstatic method 'text' failed for class '7' when called with 1 arguments ([Index=1, Type=String[], Value=System.String[]], )
[2021-06-04T21:21:04.2911360Z] [wn2-hdic5c] [Error] [JvmBridge] org.apache.spark.sql.AnalysisException: Path does not exist: wasbs://hdic5c1a801nam@deststorageefafdoyri6n6m.blob.core.windows.net/user/livy/foo;
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary$1.apply(DataSource.scala:558)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary$1.apply(DataSource.scala:545)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.immutable.List.flatMap(List.scala:355)
	at org.apache.spark.sql.execution.datasources.DataSource.org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary(DataSource.scala:545)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:359)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
	at org.apache.spark.sql.DataFrameReader.text(DataFrameReader.scala:714)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.api.dotnet.DotnetBackendHandler.handleMethodCall(DotnetBackendHandler.scala:165)
	at org.apache.spark.api.dotnet.DotnetBackendHandler$$anonfun$handleBackendRequest$1.apply$mcV$sp(DotnetBackendHandler.scala:105)
	at org.apache.spark.api.dotnet.ThreadPool$$anon$1.run(ThreadPool.scala:34)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[2021-06-04T21:21:04.2934692Z] [wn2-hdic5c] [Exception] [JvmBridge] JVM method execution failed: Nonstatic method 'text' failed for class '7' when called with 1 arguments ([Index=1, Type=String[], Value=System.String[]], )
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: JVM method execution failed: Nonstatic method 'text' failed for class '7' when called with 1 arguments ([Index=1, Type=String[], Value=System.String[]], )
 ---> Microsoft.Spark.JvmException: org.apache.spark.sql.AnalysisException: Path does not exist: wasbs://hdic5c1a801nam@deststorageefafdoyri6n6m.blob.core.windows.net/user/livy/foo;
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary$1.apply(DataSource.scala:558)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary$1.apply(DataSource.scala:545)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.immutable.List.flatMap(List.scala:355)
	at org.apache.spark.sql.execution.datasources.DataSource.org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary(DataSource.scala:545)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:359)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
	at org.apache.spark.sql.DataFrameReader.text(DataFrameReader.scala:714)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.api.dotnet.DotnetBackendHandler.handleMethodCall(DotnetBackendHandler.scala:165)
	at org.apache.spark.api.dotnet.DotnetBackendHandler$$anonfun$handleBackendRequest$1.apply$mcV$sp(DotnetBackendHandler.scala:105)
	at org.apache.spark.api.dotnet.ThreadPool$$anon$1.run(ThreadPool.scala:34)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

   --- End of inner exception stack trace ---
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object arg0)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallNonStaticJavaMethod(JvmObjectReference objectId, String methodName, Object arg0)
   at Microsoft.Spark.Interop.Ipc.JvmObjectReference.Invoke(String methodName, Object arg0)
   at Microsoft.Spark.Sql.DataFrameReader.LoadSource(String source, String[] paths)
   at Microsoft.Spark.Sql.DataFrameReader.Text(String[] paths)
   at Canary.Hdi.Program.Main(String input, String appName) in C:\src\aml-ds\recipes\signed-components\canary-hdi\Program.cs:line 20
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass6_0.<<ConfigureConsole>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
SystemLog:ERROR:spark_net:Error message: An error occurred while calling z:org.apache.spark.deploy.dotnet.DotnetRunner.main.

SystemLog:ERROR:spark_net:Java exception: org.apache.spark.SparkUserAppException: User application exited with 1
SystemLog: Traceback (most recent call last):
SystemLog:   File "run.py", line 158, in main
SystemLog:     run(args, log)
SystemLog:   File "run.py", line 124, in run
SystemLog:     run_spark_net(spark, "canary-hdi.zip", "canary-hdi", ["--input", args.input_path])
SystemLog:   File "/mnt/resource/hadoop/yarn/local/usercache/livy/appcache/application_1621957744250_0009/container_e02_1621957744250_0009_01_000001/__pyfiles__/spark_net.py", line 72, in run_spark_net
SystemLog:     spark._jvm.org.apache.spark.deploy.dotnet.DotnetRunner.main(dotnet_args_java)
SystemLog:   File "/usr/hdp/current/spark2-client/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
SystemLog:     answer, self.gateway_client, self.target_id, self.name)
SystemLog:   File "/usr/hdp/current/spark2-client/python/pyspark/sql/utils.py", line 63, in deco
SystemLog:     return f(*a, **kw)
SystemLog:   File "/usr/hdp/current/spark2-client/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
SystemLog:     format(target_id, ".", name), value)
SystemLog: py4j.protocol.Py4JJavaError: <unprintable Py4JJavaError object>
Traceback (most recent call last):
  File "run.py", line 163, in <module>
    main()
  File "/usr/bin/anaconda/envs/py37/lib/python3.7/site-packages/shrike/compliant_logging/exceptions.py", line 346, in wrapper
    caught_err,
  File "/usr/bin/anaconda/envs/py37/lib/python3.7/site-packages/shrike/compliant_logging/exceptions.py", line 294, in print_prefixed_stack_trace_and_raise
    raise scrubbed_err  # type: ignore
  File "/usr/bin/anaconda/envs/py37/lib/python3.7/site-packages/shrike/compliant_logging/exceptions.py", line 334, in wrapper
    return function(*func_args, **func_kwargs)
  File "run.py", line 158, in main
    run(args, log)
  File "run.py", line 124, in run
    run_spark_net(spark, "canary-hdi.zip", "canary-hdi", ["--input", args.input_path])
  File "/mnt/resource/hadoop/yarn/local/usercache/livy/appcache/application_1621957744250_0009/container_e02_1621957744250_0009_01_000001/__pyfiles__/spark_net.py", line 72, in run_spark_net
    spark._jvm.org.apache.spark.deploy.dotnet.DotnetRunner.main(dotnet_args_java)
  File "/usr/hdp/current/spark2-client/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/usr/hdp/current/spark2-client/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/usr/hdp/current/spark2-client/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: <exception str() failed>
```

**Comment by dkmiller** [comment]
The internal package [Microsoft.Substrate.AI.OdinmlHDI.ppe](https://o365exchange.visualstudio.com/O365%20Core/_packaging?_a=package&feed=Common&package=Microsoft.Substrate.AI.OdinmlHDI.ppe&protocolType=NuGet&version=16.4.1&view=overview) contains a script [DotnetSpark-0.4.0.py](https://o365exchange.visualstudio.com/O365%20Core/_git/EuclidOdinML?path=%2Fsources%2Fdev%2FProjects%2Fdotnet%2FOdinMLDotNet%2FDotnetSpark-0.4.0.py&_a=contents&version=GBmaster) with very similar functionality.
